openapi: 3.0.3
info:
  title: DotAAS Part 2 | HTTP/REST | AASX File Server
  description: The AASX file server as part of Details of the Asset Administration Shell Part 2
  contact:
    name: Michael Hoffmeister, Torben Miny, Andreas Orzelski, Manuel Sauer, Constantin Ziesche
  version: V1.0RC01
  termsOfService: https://github.com/admin-shell-io/aas-specs
paths:
  '/packages':
    get:
      tags:
      - AASX File Server Interface
      summary: Returns a list of available AASX packages at the server
      operationId: GetAllAASXPackageIds
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetAllAASXPackageIds/1/0/RC02
      parameters:
      - name: aasId
        in: query
        description: The Asset Administration Shellâ€™s unique id (BASE64-URL-encoded)
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Requested package list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/PackageDescription'
    post:
      tags:
      - AASX File Server Interface
      summary: Stores the AASX package at the server
      operationId: PostAASXPackage
      x-semanticIds:
        - https://admin-shell.io/aas/API/PostAASXPackage/1/0/RC02
      requestBody:
        description: AASX package
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                aasIds:
                  type: array
                  items:
                    $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/Identifier'
                file:
                  type: string
                  format: binary
                fileName:
                  type: string
            encoding:
              file:
                contentType: application/asset-administration-shell-package
        required: true
      responses:
        "201":
          description: AASX package stored successfully
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/PackageDescription'
  '/packages/{packageId}':
    get:
      tags:
      - AASX File Server Interface
      summary: Returns a specific AASX package from the server
      operationId: GetAASXByPackageId
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetAASXByPackageId/1/0/RC02
      parameters:
      - name: packageId
        in: path
        description: The package Id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Requested AASX package
          headers:
            X-FileName:
              schema:
                type: string
              description: Filename of the package
          content:
            application/asset-administration-shell-package:
              schema:
                type: string
                format: binary
    put:
      tags:
      - AASX File Server Interface
      summary: Updates the AASX package at the server
      operationId: PutAASXByPackageId
      x-semanticIds:
        - https://admin-shell.io/aas/API/PutAASXByPackageId/1/0/RC02
      parameters:
      - name: packageId
        in: path
        description: The Package Id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: true
        schema:
          type: string
      requestBody:
        description: AASX package
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                aasIds:
                  type: array
                  items:
                    $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/Identifier'
                file:
                  type: string
                  format: binary
                fileName:
                  type: string
            encoding:
              file:
                contentType: application/asset-administration-shell-package
        required: true
      responses:
        "204":
          description: AASX package updated successfully
    delete:
      tags:
      - AASX File Server Interface
      summary: Deletes a specific AASX package from the server
      operationId: DeleteAASXByPackageId
      x-semanticIds:
        - https://admin-shell.io/aas/API/DeleteAASXByPackageId/1/0/RC02
      parameters:
      - name: packageId
        in: path
        description: The Package Id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: true
        schema:
          type: string
      responses:
        "204":
          description: Deleted successfully