name: Check-title-and-description-of-pull-request

on: 
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  Check-title-and-description-of-pull-request:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      - name: Check the title and description of the pull request
        uses: mristin/opinionated-commit-message@v3.0.0
        with:
          path-to-additional-verbs: .github/workflows/AdditionalVerbsInImperativeMood.txt

      - name: READ HERE ON FAILURE FOR MORE INSTRUCTIONS
        if: ${{ failure() }}
        run: |
          Write-Host (
            "The title and the description of your pull request do not fit our style guide. " +
            "Please inspect carefully the error messages above and edit the pull request. " +
            "Since we are always squashing before merge, you can leave the commit messages as-are.`n`n" +
            "See the following page for more information about the style of the commit messages: " +
            "https://github.com/admin-shell-io/aas-specs/blob/master/CONTRIBUTING.md#recommendation-for-commit-messages"
          )
